title = "Lewis Coleman"
baseURL = "https://example.com"
languageCode = "en-us"
theme = "gohugo-theme-ananke"

MetaDataFormat = "yaml"
DefaultContentLanguage = "en"
SectionPagesMenu = "main"
Paginate = 6 # this is set low for demonstrating with dummy content. Set to a higher number
googleAnalytics = ""
enableRobotsTXT = true

[sitemap]
  changefreq = "monthly"
  priority = 0.5
  filename = "sitemap.xml"

[params]
  favicon = ""
  description = "A Chemical turn Software Engineer"
  facebook = ""
  twitter = "https://twitter.com/lewic23"
  instagram = ""
  youtube = ""
  github = "https://github.com/lewisc2303"
  gitlab = ""
  linkedin = "https://www.linkedin.com/in/lewis-coleman-50266ba5/"
  mastodon = ""
  # choose a background color from any on this page: http://tachyons.io/docs/themes/skins/ and preface it with "bg-"
  background_color_class = "bg-black"
  featured_image = "/images/MunichCity.jpg"
  recent_posts_number = 3
  show_reading_time = true